FROM openvino/ubuntu20:2021.4

ENV DEBIAN_FRONTEND=noninteractive

ENV HTTP_PROXY "http://127.0.0.1:7890" 
ENV HTTPS_PROXY "http://127.0.0.1:7890"

USER root
RUN apt-get -y update && apt-get upgrade -y \
    && apt-get install -y --fix-missing \
    apt-utils software-properties-common \
    pkg-config \
    vim \
    git \
    wget unzip\
    libgtk2.0-dev \
    libgtk-3-dev \
    libavcodec-dev \
    libavformat-dev \
    libjpeg-dev \
    libswscale-dev \
    libtiff5-dev  \
    curl \
    rsync \
    ccache htop\
    ssh \
    libgoogle-glog-dev libgflags-dev \
    libatlas-base-dev \
    libeigen3-dev \
    libsuitesparse-dev \
    libcanberra-gtk-module python3 python3-dev python3-numpy python3-pip \
    libssl-dev libpng-dev libwebp-dev libavresample-dev libavutil-dev libopenexr-dev \
    iproute2 can-utils python3-can python3-setuptools libssl-dev \
    && add-apt-repository ppa:ubuntu-toolchain-r/test \
    && apt-get -y purge gcc g++ cmake make gdb build-essential && apt-get -y autoremove \
    && apt-get -y install make gdb g++-11 gcc-11 \
    # 设置gcc和g++为默认的编译器
    && ln -s /usr/bin/g++-11 /usr/bin/g++ \
    && ln -s /usr/bin/gcc-11 /usr/bin/gcc \
    && ln -s /usr/bin/g++-11 /usr/bin/c++ \
    && ln -s /usr/bin/gcc-11 /usr/bin/cc \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /cmake && cd /cmake && wget -t 0 https://github.com/Kitware/CMake/releases/download/v3.23.1/cmake-3.23.1.tar.gz && tar -vxf cmake-3.23.1.tar.gz && cd cmake-3.23.1 && ./bootstrap -- -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX=/usr && make install -j 14 && rm -r /cmake

# 迈德威视
COPY mv_sdk /mv_sdk
RUN mkdir -p /etc/udev/rules.d/ && cd /mv_sdk && ./install.sh && rm -rf /mv_sdk

# fmt安装配置
RUN cd / && git clone https://github.com/fmtlib/fmt.git/ && mkdir fmt/build && cd fmt/build \
	&& cmake .. && make -j 12 && make install && rm -rf /fmt

# spdlog手动安装
RUN cd / && git clone https://github.com/gabime/spdlog.git && mkdir spdlog/build \
    && cd spdlog/build \
	&& cmake .. && make -j 12 && make install && rm -rf /spdlog

# ceres安装（eigen3）
RUN cd / && git clone https://ceres-solver.googlesource.com/ceres-solver && mkdir ceres-solver/ceres-bin/ && cd ceres-solver/ceres-bin && cmake .. && make -j 12 && make install && rm -rf /ceres-solver && ln -s /usr/include/eigen3/Eigen /usr/include/Eigen && ln -s /usr/include/eigen3/unsupported /usr/include/unsupported

# zsh安装与配置
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.2/zsh-in-docker.sh)" -- \
    -t jispwoso \
    -a HYPHEN_INSENSITIVE="true" \
    -a DISABLE_UNTRACKED_FILES_DIRTY="true" \
    -a COMPLETION_WAITING_DOTS="true" \
    -p git \
    -p z \
    -p colored-man-pages \
    -p sudo \
    -p extract \
    -p copypath \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-syntax-highlighting

# 设置openvino环境变量在zsh启动时刷新
RUN echo 'source ${INTEL_OPENVINO_DIR}/bin/setupvars.sh' >> /root/.zshrc && \
    echo 'export LIBVA_DRIVER_NAME=iHD' >> /root/.zshrc && \
    echo 'export LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri' >> /root/.zshrc && \
    echo 'export GST_VAAPI_ALL_DRIVERS=1' >> /root/.zshrc && \
    rm /usr/local/bin/cmake


ENV HTTP_PROXY "" 
ENV HTTPS_PROXY ""
WORKDIR /root   
